services:
  - type: web
    name: docutranslate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn docutranslate.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8010
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /api/meta
    autoDeploy: true
